### PR TITLE
Remove cpp-ethereum (and leave deprecation notice)

### LINKED ISSUE #161: Error Installing C++ for Ethereum on Mac
Mac OS High Sierra Version: 10.13.3 (17D102)

```
Chases-MacBook-Pro-2017:~ chase$ brew tap ethereum/ethereum
Chases-MacBook-Pro-2017:~ chase$ brew install cpp-ethereum
brew linkapps cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/chase/Library/Caches/Homebrew/cpp-ethereum--git'...
remote: Counting objects: 614, done.
remote: Compressing objects: 100% (590/590), done.
remote: Total 614 (delta 80), reused 156 (delta 9), pack-reused 0
Receiving objects: 100% (614/614), 1.20 MiB | 4.57 MiB/s, done.
Resolving deltas: 100% (80/80), done.
==> Checking out branch develop
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
Last 15 lines from /Users/chase/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:90 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180330-41832-enzfhg/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

Chases-MacBook-Pro-2017:~ chase$ brew linkapps cpp-ethereum
Warning: Calling 'brew linkapps' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cmd/linkapps.rb:18:in `linkapps'

Error: No such keg: /usr/local/Cellar/cpp-ethereum
```

### LINKED ISSUE #216: Remove Aleth / cpp-ethereum from Homebrew

### PR DESCRIPTION
**Pull request by axic**
Closes #216. Closes #161.

### CODE REVIEW

File: cpp-ethereum.rb [hunk 1]
```diff
@@ -17,24 +17,7 @@ class CppEthereum < Formula
...
-  def install
-    system "cmake", ".", *std_cmake_args, "-DVMTRACE=ON"
-    system "make"
-    system "make", "install"
-  end
-
-  test do
-    system "#{bin}/aleth", "--version"
-  end
+  odie "cpp-ethereum has been removed from Homebrew. Please install binary release from https://github.com/ethereum/aleth/relases"
```
Comment (axic) [inline cpp-ethereum.rb]: Left this message here because there's no direct way to mark removed/deprecated packages.

Homebrew only has two files:
- `formula_renames.json` for renaming
- `tap_migrations.json` when a package moved to a different repository

File: cpp-ethereum.rb [hunk 2]
```diff
@@ -17,24 +17,7 @@ class CppEthereum < Formula
...
-  def install
-    system "cmake", ".", *std_cmake_args, "-DVMTRACE=ON"
-    system "make"
-    system "make", "install"
-  end
-
-  test do
-    system "#{bin}/aleth", "--version"
-  end
+  odie "cpp-ethereum has been removed from Homebrew. Please install binary releases from https://github.com/ethereum/aleth/relases"
```
Comment (chfast) [inline cpp-ethereum.rb]:
```suggestion
  odie "Aleth (formerly cpp-ethereum) has been removed from Homebrew. Please install binary releases from https://github.com/ethereum/aleth/releases"
```

Comment (axic) [reply cpp-ethereum.rb]: Fixed.

**Comment by chfast** [comment]
Is it enough to just merge it now?

**Comment by karalabe** [comment]
@axic @chfast I think this PR borked something: https://github.com/ethereum/go-ethereum/issues/19335

**Comment by nonsense** [comment]
Looks like `odie` is throwing an `Exception`, but also `version` field is required for taps.

**Comment by chfast** [comment]
Whatever it was suppose to do, you can remove it.

**Comment by axic** [comment]
Weird, I must have had a different brew version because the change worked here.
